version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g serverless
  build:
    commands:
      - echo "Deploying serverless app"
      - cd test-serverless-project
      - serverless deploy
      - echo "Done!"